🚀 1단계 - JPA 전환
next-step/spring-roomesacpe-waiting pull request #15
Opened 2024-06-26 15:55 UTC by JohnPrk

안녕하세요 최현구 리뷰어님! 저는 매번 JPA로 코드를 짰었는데,,, jdbc에서 JPA로 마이그레이션 하는 느낌이 되게 새로웠습니다. 미션 진행하면서 궁금한 점들은 아래에 남겨두겠습니다. 혹시나 미흡한 점이 있다면 얼마든지 피드백해주셔도 됩니다!!!! 좋은 인사이트 기대하겠습니다! 오늘도 좋은 밤 되십쇼 :)

## 구현 사항
* [ ] 뼈대 코드 덮어쓰기
* [ ] 기존 jdbc 데이터스키마 삭제
* [ ] 각 도메인 엔티티화 및 연관관계 설정
* [ ] 사용자 관련 JPA 구현체 생성
* [ ] 테마 관련 JPA 구현체 생성
* [ ] 시간 관련 JPA 구현체 생성
* [ ] api 패키지 내로 이동(지난 미션 때 놓쳤던 부분)
* [ ] 예약 관련 연관관계 재설정(다대다 -> 일대일)
* [ ] 예약 관련 JPA 구현체 생성

## 질문

### 인터페이스 관련 jdbc, JPA 구현체 질문
* 제가 사실,, jdbc에서 JPA로 마이그레이션이 처음이라서 그럴 수는 있는데,,, 서비스에서 하나의 인터페이스(예 : TimeRepository)를 통해서 구현체 TimeJdbcRepository, 인터페이스 구현체 TimeJpaRepository를 각각 만들어서 생성자 주입시(DI)에 둘 중에 한 구현체를 넣고 싶다고 생각했습니다. 
```java
public class TimeService {

    private final TimeRepository timeRepository;

    public TimeService(TimeRepository timeRepository) {
        this.timeRepository = timeRepository;
    }
}

public class TimeJdbcRepository implements TimeRepository {
...
}

public class TimeJpaRepository implements TimeRepository {
...
}

``` 
* 그런데, jdbc는 크게 문제가 없는데, jpa의 경우 실제 구현부가 JpaRepository이거나 CustomRepository이기 때문에 아예 새로운 인터페이스를 만들 수 밖에 없었습니다.
```java
package roomescape.domain.time.domain.repository;

import org.springframework.data.jpa.repository.JpaRepository;
import roomescape.domain.time.domain.Time;

import java.util.List;

public interface TimeJpaRepository extends JpaRepository<Time, Long>, TimeRepositoryCustom {
    Time save(Time time);

    List<Time> findAll();

    void delete(Time time);

    List<Time> findByThemeIdAndDate(String themeId, String date);
}

```

* 이렇게 되니 '언제든 jdbc 혹은 jpa로 바꿔 끼울 수 있는 코드가 아니라 ,, 그냥 각각의 기술에 한정되는 코드가 아닌가'라는 생각이 들었습니다. 혹시 이 부분에 대해서 리뷰어님의 의견이 궁금하고 제가 모르는 부분이 많을 수 있으니 좋은 아이디어나 힌트를 주시면 감사하겠습니다!

<br>

### 연관관계 질문
* JPA로 미션을 진행하면서 '사용자, 시간, 테마, 예약 엔티티 관련해서 연관관계가 잘못된게 아닌가?'라는 생각이 들었습니다.
* 일반적인 관점에서 저는 '예약과 관련된 사용자, 시간, 테마 엔티티 모두 다대다 관계가 되어야하지 않을까?'라고 생각을 했습니다.
* 물론, 2주차까지 진행되어온 미션에서 그에 대한 요구사항이 따로 없었기 때문에 크게 생각을 안 했는데, JPA로 전환을 해보니 이상하다는 느낌을 조금 받았던 것 같습니다.
* 물론 ,,, 현업이라면 추후에 요구사항이 바뀔 가능성이 아주 많을듯합니다,,, 그리고 그에 따른 엔티티 재설계 및 데이터스키마 이전이 아주 피곤해질꺼 같다고 생각이 듭니다 ,,,
* 이에 대해서 리뷰어님은 어떻게 생각하시나요? 저는 현업에 있을 때,, 한 번 재설계 해봤는데,,, 너무 힘든 작업이더라구요 ,,ㅠㅠ 그래서 개인적으로는 JPA로 구현을 할 때는 엔티티 설계부터 차근차근 했었던 것 같습니다.

2024-06-27 09:46 UTC, Hyeon9mak requested changes
안녕하세요 민욱님! JPA 전환 잘 진행해주셨습니다 👍 

민욱님이 말씀해주신 것처럼 JPA entity 가 유지보수 단계에서 큰 불편을 주기 때문에
저는 JPA 를 딥하게 사용하는걸 선호하지 않습니다.
JPA entity 는 가능하면 테이블을 형상을 나타내는 수준으로만 사용하고,
비즈니스 연관관계 등은 모두 domain 객체를 별도로 만들어 표현해줍니다.

민욱님도 잘 아시겠지만 프로그램을 만들기 이전에
도메인(비즈니스)에 대한 이해가 정말 중요한거 같습니다.
자칫 요구사항을 잘못 이해하거나, 현실에 있을법한 개념을 깜빡 놓치게 되면
이번처럼 피곤한 일이 발생하는거 같아요..!

다행히 질문주신 N:M 연관관계 설정은 테이블을 추가로 만들고,
코드를 조금만 더 추가해주면 될 것 같습니다.

몇 가지 코멘트도 남겼으니  확인해주세요!

2024-06-27 09:46 UTC, Hyeon9mak commented on src/main/java/roomescape/domain/member/api/login/ApiLoginController.java
> +        return ResponseEntity.ok().header(HttpHeaders.SET_COOKIE, responseCookie.toString()).build();
60 이 어떤 단위인지 주석을 남겨두거나, 상수로 분리하여 이름을 붙여두면 동료 개발자들이 큰 도움을 얻겠네요!

2024-06-27 09:46 UTC, Hyeon9mak commented on src/main/java/roomescape/domain/member/domain/Member.java
> +    }
객체의 값을 꺼내지 않고 메세지를 보내기 👍 👍

2024-06-27 09:46 UTC, Hyeon9mak commented on src/main/java/roomescape/domain/member/domain/repository/MemberJdbcRepository.java
> +
simple jdbc insert 를 활용하는 방법도 있겠네요 😄

2024-06-27 09:46 UTC, Hyeon9mak commented on src/main/java/roomescape/domain/member/domain/repository/MemberJdbcRepository.java
> +        return Optional.of(members.get(0));
row mapper 를 멤버변수로 분리하면 중복 코드를 제거하기 좋겠네요 😄

2024-06-27 09:46 UTC, Hyeon9mak commented on src/main/java/roomescape/domain/member/domain/repository/MemberJpaRepository.java
> +@Repository
`@Repository` 어노테이션이 필요할까요? 🤔

2024-06-27 09:46 UTC, Hyeon9mak commented on src/main/java/roomescape/domain/member/domain/repository/MemberRepository.java
> +
<img width="1272" alt="image" src="https://github.com/next-step/spring-roomescape-waiting/assets/37354145/7cfee304-709f-4ca9-8198-9750928b3beb">

이런 식으로 구현해보면 질문주신 내용을 해소할 수 있을거 같아요 😄

2024-06-27 09:46 UTC, Hyeon9mak commented on src/main/java/roomescape/domain/member/domain/repository/MemberRepositoryCustomImpl.java
> +    }
spring data jpa 가 도입되어 있는데, 엔티티 매니저를 직접 다루신 이유가 있을까요?

2024-06-27 09:46 UTC, Hyeon9mak commented on src/main/java/roomescape/domain/reservation/domain/Reservation.java
> +    private Member member;
중간 테이블을 추가하고, 중간 엔티티를 추가하고, N:M 관계를 매핑시켜주면 되지 않을까요?
우려하신만큼 수정 범위가 크진 않을 것 같아요!

2024-06-27 09:46 UTC, Hyeon9mak commented on src/main/resources/static/js/user-reservation.js
> +        themeSlots.appendChild(createSlot('theme', name, themeId));
작업이 완료되었다면 주석 제거!
 동료 개발자가 헷갈리겠어요 😢

2024-06-28 14:52 UTC, JohnPrk commented
안녕하세요 리뷰어님! 피드백에 대한 답변이나 궁금증은 기존의 피드백에 남겨두겠습니다.

이 번에도 리뷰 잘 부탁드리겠습니다 :)

2024-06-28 14:55 UTC, JohnPrk commented on src/main/java/roomescape/domain/member/api/login/ApiLoginController.java
> +        return ResponseEntity.ok().header(HttpHeaders.SET_COOKIE, responseCookie.toString()).build();
쿠키 만료시간을 3600초(1시간)로 변경했고 COOKIE_EXPIRATION_SECONDS 상수화 작업 했습니다.

2024-06-28 14:57 UTC, JohnPrk commented on src/main/java/roomescape/domain/member/domain/repository/MemberJdbcRepository.java
> +
처음 들어보는 키워드라서 구글링 했는데,,, 리뷰어님의 블로그가 나오니 굉장히 반가웠습니다!
https://hyeon9mak.github.io/easy-insert-with-simplejdbcinsert/

스프링에서 제공하는 공식문서도 한 번 읽어보겠습니다!!! -> https://docs.spring.io/spring-framework/reference/data-access/jdbc/simple.html

2024-06-28 14:57 UTC, JohnPrk commented on src/main/java/roomescape/domain/member/domain/repository/MemberJdbcRepository.java
> +        return Optional.of(members.get(0));
중복 코드 제거 완료했습니다!

2024-06-28 14:59 UTC, JohnPrk commented on src/main/java/roomescape/domain/member/domain/repository/MemberJpaRepository.java
> +@Repository
기존에 XXXRepositoryCustomImpl 클래스에서 @Repository를 가지고 있었기 때문에 @Repository 없애도 문제없이 동작했습니다,,,

2024-06-28 15:08 UTC, JohnPrk commented on src/main/java/roomescape/domain/member/domain/repository/MemberRepository.java
> +
리뷰어님이 알려주신 방법과 주변 지인 분들께 조언을 바탕으로 기존의 JPA 구현체가 JpaRepository<Class, Id>와 JpaRepositoryCustom를 상속 받는 구조로 사용하려고 했으나 도저히 어떻게 설계해야할지 모르겠어서 포기했습니다ㅎㅎㅎ

이에 대한 대안으로 하나의 Repository 인터페이스를 상속받는 JdbcRepository 클래스와 순수 JPA로 구현한 JpaRepository 클래스로 만들어서 진행했습니다. 이 부분에 대한 다른 방법이 혹시나 있다면 알려주시면 정말 감사하겠습니다!

2024-06-28 15:10 UTC, JohnPrk commented on src/main/java/roomescape/domain/member/domain/repository/MemberRepositoryCustomImpl.java
> +    }
가능하면 2번째 미션 때 SpringDataJpa를 도입하고, 시간이 된다면 3번째 미션 때 QueryDSL을 도입해보려고 계획 중에 있습니다.

2024-06-28 15:10 UTC, JohnPrk commented on src/main/resources/static/js/user-reservation.js
> +        themeSlots.appendChild(createSlot('theme', name, themeId));
주석 제거 완료했습니다!

2024-06-28 15:26 UTC, JohnPrk commented on src/main/java/roomescape/domain/reservation/domain/Reservation.java
> +    private Member member;
중간 테이블로 다대일, 일대다를 만드는 것까지는 큰 문제가 없는데, 몇 가지 문제가 있지 않나 생각이 듭니다.
1. fetch쿼리로 여러 개의 각 도메인(시간, 테마, 사용자)를 들고 올 때, 예약 랜더링 페이지에서 보여주는 값은 무엇으로 해야할지 대한 문제가 있을 것. 같습니다.
```java
package roomescape.domain.reservation.domain.repository;

import jakarta.persistence.EntityManager;
import jakarta.persistence.TypedQuery;
import org.springframework.context.annotation.Primary;
import org.springframework.stereotype.Repository;
import roomescape.domain.reservation.domain.Reservation;

import java.util.List;
import java.util.Optional;


@Repository
@Primary
public class ReservationJpaRepository implements ReservationRepository {

    private static final String FIND_BY_ID_SQL = """
            SELECT r
            FROM Reservation r
            JOIN FETCH r.theme t
            JOIN FETCH r.time ti
            JOIN FETCH r.member m
            WHERE r.id = :id
            """;
    private static final String ID = "id";

    private final EntityManager entityManager;
    
    ...

    public ReservationJpaRepository(EntityManager entityManager) {
        this.entityManager = entityManager;
    }

    @Override
    public Optional<Reservation> findById(long reservationId) {
        TypedQuery<Reservation> query = entityManager.createQuery(FIND_BY_ID_SQL, Reservation.class);
        query.setParameter(ID, reservationId);
        return Optional.of(query.getSingleResult());
    }
}

``` 
2. 중간 테이블로 생김으로 인해서 서비스 레이어에서 연관관계 편의 메서드도 만들어야할 것 같습니다.
3. 랜더링 페이지에서 보여주는 값과 JPA의 값이 다르기 때문에 DTO 변환도 꽤나 번거롭지 않을까 합니다.

* 이 것과 별개로 제가 아직 엔티티와 도메인을 함께 사용해본 경험이 없는데, 이에 대한 장, 단점이 어떻게 될까요? 혹시나 주의해야할 점이 있을까요?

2024-06-29 09:29 UTC, Hyeon9mak approved these changes
안녕하세요 민욱님~! 피드백 잘 반영해주셨습니다.
추가로 질문 주신 부분에 대해서 조금 더 상세한 코멘트 남겼으니 확인해주세요!
다음 단계 진행하면서 함께 확인해주시면 될거 같습니다.
다음 단계에서 만나요!

2024-06-29 09:29 UTC, Hyeon9mak commented on src/main/java/roomescape/domain/member/api/login/ApiLoginController.java
> +    private static final int COOKIE_EXPIRATION_SECONDS = 3600;
😉 👍 
3600 이 60분, 1시간을 의미한다는 주석까지 남겨주시면 금상첨화!

2024-06-29 09:29 UTC, Hyeon9mak commented on src/main/java/roomescape/domain/member/domain/repository/MemberJdbcRepository.java
> +        this.jdbcInsert = new SimpleJdbcInsert(dataSource)
> 리뷰어님의 블로그가 나오니 굉장히 반가웠습니다!

🙇‍♂️ 👍 

제 블로그는 감사하지만 공식문서가 역시 최고죠! ㅎㅎ

2024-06-29 09:29 UTC, Hyeon9mak commented on src/main/java/roomescape/domain/member/domain/repository/MemberJpaRepository.java
> +@Repository
그렇다면 제거해주시면 되겠네요!! 👍 👍

2024-06-29 09:29 UTC, Hyeon9mak commented on src/main/java/roomescape/domain/member/domain/repository/MemberRepository.java
> +
```java
public class MemberRepositoryImpl implements MemberRepository {
    
    private final MemberJdbcRepository memberJdbcRepository;
    private final MemberJpaRepository memberJpaRepository;

    public MemberRepositoryImpl(MemberJdbcRepository memberJdbcRepository, MemberJpaRepository memberJpaRepository) {
        this.memberJdbcRepository = memberJdbcRepository;
        this.memberJpaRepository = memberJpaRepository;
    }

    @Override
    public Optional<Member> findByEmailAndPassword(String email, String password) {
        // TODO: implement
    }

    @Override
    public Optional<Member> findById(Long memberId) {
        // TODO: implement
    }

    @Override
    public Long save(Member member) {
        // TODO: implement
    }

    @Override
    public List<Member> findAll() {
        // TODO: implement
    }

    @Override
    public Long updateAdminRole(Long id) {
        // TODO: implement
    }
}
```

요런식의 구현방식을 말씀드리고 싶었어요!
그럼 JpaRepository 는 JpaRepository 대로 자유롭게 활용하고,
JdbcRepository 도 활용할 수 있죠.
그리고 MemberRepository interface 를 의존하는 곳에서는 MemberRepository interface 외 내부 구현 사항을 알 필요가 없어지구요!

2024-06-29 09:30 UTC, merged