Step3 예약 대기 기능 구현
next-step/spring-roomesacpe-waiting pull request #30
Opened 2024-07-08 08:57 UTC by parkjun5

안녕하세요!

3단계 예약 대기 구현하여 리뷰 요청드립니다.

늦게 제출하여서 죄송합니다.
어제까지 기한이였지만 이사를 하느라 정신이 없어서 이제야 제출하네요.😭
늦게나마 리뷰 잘 부탁드리겠습니다. 

리뷰간 질문드리고 싶은 것은 예약 대기의 순번을 계산하던 중 정확히 똑같은 시간에 들어와서 생성된 예약 대기의 순번은 어떻게 게산하는 것이 좋을까요?

ID값으로 비교하기엔 만약 UUID를 ID로 사용하는 경우 등 처리 못하는 경우가 발생할 듯합니다.
제일 좋은 방법은 `@Version` 을 붙이는등 동시성을 제어해 한번에 저장되지 않도록 하는 것이라고 생각이 드는데요. 
리뷰어님은 어떻게 생각하시나요?

2024-07-10 12:17 UTC, boorownie requested changes
안녕하세요! 리뷰 대타로 찾아온 류성현입니다!
대기시간이 길어지는 것 같아서 스리슬쩍 대신 리뷰를 진행했습니다 :) 

코드를 체계적으로 잘 구현해주셨는데요!
특별히 코멘트 드릴 부분은 없지만 추가로 생각해보면 좋을 부분 위주로 질문을 코멘트로 남겼습니다.
그리고 요구사항 중 확인이 안 된 부분에 대해서도 질문을 남겼으니 확인해주세요~

2024-07-10 12:17 UTC, boorownie commented on src/main/java/roomescape/apply/reservationwaiting/application/ReservationWaitingFinder.java
> +            long waitingPosition = waitingPositionCalculator.calculateByReservationWaiting(it);
calculateByReservationWaiting이 호출될 때 마다 repository를 통해서 조회가 되고 있는데요,
waiting 목록을 한번에 조회해 온 뒤 계산해서 순서를 계산하는 것과 비교했을 때 어떤 차이가 있을까요?

2024-07-10 12:17 UTC, boorownie commented on src/main/java/roomescape/apply/reservationwaiting/ui/ReservationWaitingController.java
> +public class ReservationWaitingController {
혹시 예약 대기 취소 기능도 구현하셨을까요?

2024-07-10 12:17 UTC, boorownie commented on src/main/java/roomescape/apply/reservationwaiting/ui/ReservationWaitingController.java
> +public class ReservationWaitingController {
예약 취소 시 예약 대기가 있는 경우 단순히 예약만 제거해주게되면 예약 대기가 있지만 새로 예약을 하는 정책상 빈틈이 발생할 수 있는데요~ 기존에 있던 예약 취소 기능이 호출될 때 어떤 플로우로 처리가 되면 좋을까요?

2024-07-10 12:17 UTC, boorownie commented on src/main/java/roomescape/apply/reservationwaiting/application/WaitingPositionCalculator.java
> +        return waitingPosition + 1;
크게 중요한 부분은 아니지만 메서드 이름으로 코드의 의도를 조금 더 명확히 드러낼 수 도 있습니다 :) 
```suggestion
        return updateWaitingPositionStartFromOne(waitingPosition);
```

2024-07-10 12:17 UTC, boorownie commented on src/main/java/roomescape/apply/reservationwaiting/domain/ReservationWaiting.java
> +    private Long memberId;
직접 참조와 간접 참조를 적절히 사용해주셨는데요~
혹시 어떤 기준으로 관계를 설정해주셨나요?

2024-07-10 12:17 UTC, boorownie commented on src/main/java/roomescape/apply/reservationwaiting/domain/ReservationWaiting.java
> +        reservationWaiting.waitingTime = LocalDateTime.now();
waitingTime은 지금 처럼 로직에서 설정되는 것과 디비에 들어갈 때 설정되는 것은 어떤 차이가 있을까요?
단순히 한번 생각해보시면 좋을 것 같아서 코멘트 남겨봅니다~

2024-07-10 12:17 UTC, boorownie commented on src/main/java/roomescape/apply/reservationwaiting/domain/ReservationWaiting.java
> +    public static ReservationWaiting of(ReservationTime reservationTime, Theme theme, String date, long memberId) {
정적 팩토리 메서드의 네이밍으로 of와 from을 사용중이신데 혹시 기준이 있나요?

2024-07-10 12:17 UTC, boorownie commented on src/main/java/roomescape/apply/reservationwaiting/domain/ReservationWaitingRepository.java
> +    long countByThemeIdAndDateAndTimeIdAndWaitingTimeLessThan(@Param("themeId") long themeId,
@DataJpaTest를 활용한 단위 테스트를 작성해보면 어떨까요?

2024-07-10 12:17 UTC, boorownie commented on src/test/java/roomescape/apply/reservationwaiting/infra/InMemoryReservationWaitingRepository.java
> +public class InMemoryReservationWaitingRepository implements ReservationWaitingRepository {
테스트를 위한 Repository 설정 멋집니다 👍 
궁금한게 있는데 test 환경으로 h2디비를 사용해서 jpa로 테스트를 하는 방법도 있는데
혹시 이렇게 직접 설정해주신 이유는 무엇인가요?

2024-07-10 12:17 UTC, boorownie commented on src/test/java/roomescape/apply/reservationwaiting/application/ReservationWaitingSaverTest.java
> +    void saveNewReservationWaiting() {
꼼꼼한 테스트 👍 
유스케이스에 대한 검증을 제대로 해주셨네요 👍

2024-07-11 09:02 UTC, parkjun5 commented on src/main/java/roomescape/apply/reservationwaiting/application/ReservationWaitingFinder.java
> +            long waitingPosition = waitingPositionCalculator.calculateByReservationWaiting(it);
둘의 차이는 db에 요청하는 쿼리의 수가 가장 다를 것 같아요.

 `reservationWaitingList` 의 ForEach 마다 db에 커넥션을 맺고 쿼리를 보내니 불필요한 I/O가 발생될 것 같아요.
 
 waiting 목록의 순번을 계산하기 쉬우라고 저렇게 해두었는데, 막상 쿼리를 보내보니 9번이나 발생하네요..이건 물론  `reservationWaitingList`  의 길이에 상대적으로 증가해서 위험한 코드네요!

2024-07-11 09:02 UTC, parkjun5 commented on src/main/java/roomescape/apply/reservationwaiting/ui/ReservationWaitingController.java
> +public class ReservationWaitingController {
추가했습니다!🫣

2024-07-11 09:11 UTC, parkjun5 commented on src/main/java/roomescape/apply/reservationwaiting/ui/ReservationWaitingController.java
> +public class ReservationWaitingController {
예약 취소 시 예약 대기중 가장 먼저 대기를 건 사람에게 예약을 걸어두면 좋을 것 같아요.

그런데 이 부분 생각은 했는데...막상 대기만 걸었는데 바로 예약이 되서 결제가 되면 좀 위험할 것 같아요!
예약 대기는 걸었는데, 가망 없어 보여 다른 방탈출을 이미 예약했는데 순번이 됬다고 바로 예약이 되어 버리면 문제가 발생할 것 같네요.

Status에 예약 수락 대기 혹은 결제 전 대기 같은 Status를 임시로 추가하는 것은 어떨까요?

중간 단계를 두고 이런 중간 단계에는 타임 아웃을 걸어서 이때동안이 이 사용자에게 우선권을 주고 시간이 지나면 다음 대기에게 넘어가는 방식으로 구성해보면 좋을 것 같아요. 

또 이런 프로세스를 생각하다가 궁금한 점이 생겼습니다.

만약 예약을 신청했는데, 이미 예약이 된 경우 지금은 예외를 던져주고 있습니다.
그런데 보내주신 블로그에서는 예약 대기로 생성시켜주더라구요.
이렇게되면 하나의 로직 혹은 Method에서 ReservationResponse(예약 성공 결과물) 과 ReservationWaitnigResponse(예약 대기 성공 결과물)  두개의 리턴값을 갖게되어서 결과 값을 Object나 제네릭  와일드 카드를 사용해줘야 할 것 같습니다.
제가 생각한 이런 처리가 일반적인가요? 하나의 메서드에 두가지 결과값을 가지면 나중에 추적하거나 코드를 파악하기 어려워지지 않을까 해서 궁금합니다. 🥸

2024-07-11 09:11 UTC, parkjun5 commented on src/main/java/roomescape/apply/reservationwaiting/application/WaitingPositionCalculator.java
> +        return waitingPosition + 1;
이 부분도 생각해보니 어플리케이션에서는 0부터 시작하지만 사용자에게 보여주기 위한 값 변경이니 PresetationLayer에 두는 것이 어떨까요??

2024-07-11 09:12 UTC, parkjun5 commented on src/main/java/roomescape/apply/reservationwaiting/domain/ReservationWaiting.java
> +    private Long memberId;
비지니스 로직 상에서 값을 사용할 일이 있는 객체에서는 직접 참조, 관계는 있지만 실제로 값을 사용할 일이 적고 있어도 다른 Aggregate에서 사용하는 경우에 간접 참조를 사용했습니다.

2024-07-11 09:16 UTC, parkjun5 commented on src/main/java/roomescape/apply/reservationwaiting/domain/ReservationWaiting.java
> +        reservationWaiting.waitingTime = LocalDateTime.now();
바로 생각나는 것은 서버의 시간에 따라 차이가 생길 것 같아요.

만약 서버가 여러 곳에 있고 (한국, 미국, 호주) 서버에서 now를 해준다면 각 서버에 설정된 타임 존의 now시간대가 나올 것 같아요. 그에 비해 DB는 아무래도 서버처럼 데이터가 위치가 분산되어 있지 않고(분산되어 있는 경우도 있지만..) 
대부분 서버 스펙상으로 UTC로 통일되어 있어서 관리가 좀 편하지 않을까 합니다.

2024-07-11 09:18 UTC, parkjun5 commented on src/main/java/roomescape/apply/reservationwaiting/domain/ReservationWaiting.java
> +    public static ReservationWaiting of(ReservationTime reservationTime, Theme theme, String date, long memberId) {
of는 도메인에서 주로 사용하고 클래스당 하나만 생성해서 다른 클래스에 의존하지 않는 메서드로 유지하려고 하는 것 같아요.

그에 비해 from은 DTO에 주로 사용하고 다른 클래스, 도메인에 의존해도 상관없고 여러개 만들어도 신경쓰지 않는 것 같습니다.

어떻게 보면 도메인과 DTO의 차이인 듯 하네요. of는 변경을 적게하려는 것이 큰 차이인 것 같아요.

2024-07-11 09:19 UTC, parkjun5 commented on src/main/java/roomescape/apply/reservationwaiting/domain/ReservationWaitingRepository.java
> +    long countByThemeIdAndDateAndTimeIdAndWaitingTimeLessThan(@Param("themeId") long themeId,
InMemory로만 테스트를 작성하니 실제로 쿼리가 달라는 것을 확인하지 못헀네요..추가하겠습니다.

2024-07-11 09:21 UTC, parkjun5 commented on src/test/java/roomescape/apply/reservationwaiting/infra/InMemoryReservationWaitingRepository.java
> +public class InMemoryReservationWaitingRepository implements ReservationWaitingRepository {
저 방법이 가장 쉽게 테스트를 작성해서 직접 설정합니다.

Mock하거나 Stub하거나 아니면 @DataJpaTest와 같이 빈을 올려서 테스트를 할 수 도 있지만, 아무래도 환경에 구애받는 경우도 있고 (postgresql의 text 컬럼을 사용한다던지) 테스트 속도도 느리고 

무엇보다 테스트를 작성하는데, 굉장히 시간 차이가 나더라구요. 여러 테스트를 작성해보았는데, 저는 이방법이 가장 빠르게 테스트를 작성하고 쉽게 변경할 수 있어서 선호하는 방식입니다!🙃

2024-07-15 14:16 UTC, Hyeon9mak requested changes
안녕하세요 세준님! 리뷰 코멘트를 남겼다고 생각했었는데 pending 상태로 리뷰를 멈췄었네요.. 🙏 
간단한 코멘트 몇 가지 더 얹어서 리뷰 남겼습니다.

브라운이 남겨주신 코멘트에 대해 세준님의 생각도 잘 공유해주셨고
리팩터링도 잘 진행해주신 것 같아 approve 를 하고자 고민했는데요~
혹시 질문이 추가로 있으실 수도 있을 것 같아 request changes 남길게요!

2024-07-15 14:16 UTC, Hyeon9mak commented on src/main/java/roomescape/apply/reservation/application/ReservationFinder.java
> +    public final ReservationWaitingFinder reservationWaitingFinder;
`public` 일 필요가 없어보이네요!

2024-07-15 14:16 UTC, Hyeon9mak commented on src/main/java/roomescape/apply/reservationwaiting/application/ReservationWaitingSaver.java
> +    private final ReservationWaitingRepository reservationWaitingRepository;
service 에서 finder 를 갖고 있기도 하고, saver 에서 finder 를 갖고 있기도 하고,
service 에서 repository 를 갖고 있기도 하고, saver 에서 repository 를 갖고 있기도 해서
의존간 계층관계가 어떻게 되는지 머리 속에 쉽사리 그려지지 않는데요...
저러한 명칭을 만들어주신 이유는 분명히 있다고 생각해요.
이것들의 계층관계가 한눈에 보이도록 통일이 가능할까요?

2024-07-15 14:16 UTC, Hyeon9mak commented on src/main/java/roomescape/apply/reservationwaiting/application/WaitingPositionCalculator.java
> +        return waitingPosition + 1;
계산기라 하여서 계산에만 집중한 로직을 갖고 있을줄 알았는데, repository 에서 값을 꺼내어 대기순서를 뽑아내는 로직이었군요...!

2024-07-15 14:16 UTC, Hyeon9mak commented on src/main/java/roomescape/apply/reservationwaiting/domain/ReservationWaiting.java
> +
id 를 통해 같은 대상인지 구분하는 엔티티이므로 id 에 대해서만 동등성을 부여해도 좋을거 같아요!

2024-07-15 14:16 UTC, Hyeon9mak commented on src/main/java/roomescape/apply/reservationwaiting/ui/ReservationWaitingController.java
> +public class ReservationWaitingController {
하나의 API 요청에서는 하나의 동작 결과를 보장하는게 좋겠네요 (멱등성 보장!)
그러나 멱등성보다 더 중요한 것이, "사용자에게 얼마나 좋은 가치를 전달하는가" 겠죠!
그러므로 세준님께서 고민해주신 동작 형태는 유지하면 좋겠네요~

그렇다면 두 개의 리턴 값을 가진 형태는 어떻게 해소해볼 수 있을까요?
공유해주신 형태로도 가능하겠지만
하나의 response 에 status 필드를 갖도록 해서 응답을 하는 방법도 있겠구요!
요청이 잘 수행되었다는 응답만 우선 전달해준 후,
한번 더 상태를 조회하는 API 를 호출하도록 유도해서
본인의 상태를 조회하도록 하는 방법도 있겠네요~ 😉

2024-07-15 14:16 UTC, Hyeon9mak commented on src/test/java/roomescape/apply/reservationwaiting/application/ReservationWaitingFinderJpaTest.java
> +
😉 👍 
실제 쿼리 동작을 예측할 수 있게 되었네요~

2024-07-16 11:46 UTC, parkjun5 commented on src/main/java/roomescape/apply/reservation/application/ReservationFinder.java
> +    public final ReservationWaitingFinder reservationWaitingFinder;
수정하였습니다.

2024-07-16 11:54 UTC, parkjun5 commented on src/main/java/roomescape/apply/reservationwaiting/application/ReservationWaitingSaver.java
> +    private final ReservationWaitingRepository reservationWaitingRepository;
Application 계층에서 하는 역할이 많아서 발생한 문제인 것 같아요.
기존 구조에서 비지니스 로직을 실행하면서, 동시에 데이터의 영속성을 처리하는 역할까지 맡으니 복잡해졌습니다.

어떠한 방법이 좋을까 고민하다가 CQRS Pattern을 통해  repository에 관련된 내용을 가진 중간 단계 클래스로 만들어보았어요.

## 기존  구조
### Presentation Layer  -->  Application Layer  -->   Domain Layer  

## 개선된 구조
### Presentation Layer  -->  Application Layer  --> Persistence Layer?  -->   Domain Layer  

중간 단계가 생겨서 Application에서 다른 도메인 혹은 자신의 도메인의 값을 가져오거나 저장할 떄에는 Persistence Layer을 적용해서 처리하도록 하였습니다.

저는 이런 방법을 사용하였는데, 한번 확인해주시면 감사하겠습니다!

2024-07-16 11:56 UTC, parkjun5 commented on src/main/java/roomescape/apply/reservationwaiting/application/WaitingPositionCalculator.java
> +        return waitingPosition + 1;
처음에는 모든 리스트를 값을 가져와 계산해서 Calculator라는 이름이였는데, 쿼리가 너무 많이 날라가서 바꿔버린 부분이네요.

더 이상 필요 없어진 클래스 인 것 같네요!

2024-07-16 11:57 UTC, parkjun5 commented on src/main/java/roomescape/apply/reservationwaiting/domain/ReservationWaiting.java
> +
엔티티들은 hashcode와 equals를 id로만 비교해 같은 값으로 판단하는 것이 저도 맞다고 생각해요!

2024-07-16 12:10 UTC, parkjun5 commented
그렇다면 두 개의 리턴 값을 가진 형태는 어떻게 해소해볼 수 있을까요?
     공유해주신 형태로도 가능하겠지만
     하나의 response 에 status 필드를 갖도록 해서 응답을 하는 방법도 있겠구요!
     요청이 잘 수행되었다는 응답만 우선 전달해준 후,
     한번 더 상태를 조회하는 API 를 호출하도록 유도해서
     본인의 상태를 조회하도록 하는 방법도 있겠네요~ 😉
     
이 부분도 적용해보았습니다.
예약/관리자 예약 시 이미 예약 중이라면, 예약 대기로 저장되고 CreateReservationResponse로 리턴되도록 변경했습니다.
Type을 통해 어떤 예약이 진행되었는 지도 리턴하도록 하였습니다.

이러한 방식으로  하나의 메서드에서 여러 타입을 반환하도록 처리하는 것은 생각하지 못했던 부분이라 재미있게 진행했습니다.

API를 개발할 때에, 멱등성을 보장하기 위해 하나의 동작만 작동하는 것이 이해하기 쉽고, 다른 개발자가 유지 보수하기 좋아 평소이 이런 방식을 선호했어요.

그런데 이런 상황에서는 이렇게 비지니스 규칙에 맞게 유동적으로 처리하는 API도 좋다고 생각이 듭니다.
특히 API를 사용하는 입장에서 편의성 많이 개선될 것 같아서 한번 적용해보고 싶네요

2024-07-17 09:29 UTC, Hyeon9mak approved these changes
안녕하세요 세준님! 피드백 긍정적으로 받아주셔서 감사합니다~ 
덕분에 저도 즐거운 마음으로 확인할 수 있었어요 🙇‍♂️ 

요구사항도 모두 만족된 것 같고, 피드백도 잘 반영해주셔서 마무리 하려고 합니다.
늦은 기간까지 고생 많으셨습니다!

2024-07-17 09:29 UTC, Hyeon9mak commented on src/main/java/roomescape/apply/reservation/application/handler/ReservationFinder.java
> +    private final ReservationWaitingQueryService reservationWaitingQueryService;
계층을 명확하게 나눠주신 덕분에 코드를 따라가며 구조를 이해하기 용이해졌네요~
네이밍은 세준님과 함께하시는 동료개발자분들과 컨벤션을 맞추기 나름이라고 생각해요! 😉 
잘 변경해주셨습니다 👍

2024-07-17 09:29 UTC, Hyeon9mak commented on src/main/java/roomescape/apply/reservation/ui/dto/MyReservationResponse.java
> +    }
상태를 응답하게 되었군요~ 👍

2024-07-17 09:29 UTC, merged