3단계 - 예약 대기 기능
next-step/spring-roomesacpe-waiting pull request #35
Opened 2024-07-19 02:40 UTC by eottabom

2024-07-21 10:16 UTC, byjo requested changes
유근님~ 마지막 단계도 잘 구현해주셨네요!
이미 충분히 잘 되어있어 크게 피드백 드릴 내용은 없고, 간단한 코멘트 남겨봤어요.
마지막 단계인 만큼 구현하면서 의문이 들거나 같이 이야기 해보고 싶은 내용 있다면 코멘트 남겨주세요.
과정 마무리가 얼마 남지 않았는데 마지막까지 화이팅입니다! 💪

2024-07-21 10:16 UTC, byjo commented on src/main/java/roomescape/repository/ReservationJpaRepository.java
> +	List<ReservationWithRank> findReservationsWithRankByMemberName(@Param("memberName") String memberName);
예약 대기 기능의 경우 구현 방법이 다양한데요.
이번 미션에서는 reservation 테이블에 예약과 예약 대기가 모두 담기도록 구현 하셨네요!
어떤 이유로 이런 설계를 하셨는지 그 배경을 알고싶습니다.

2024-07-21 10:16 UTC, byjo commented on src/main/java/roomescape/service/ReservationService.java
> +		var theme = this.themeService.getThemeById(themeId);
현재는 한 사람이 예약 및 무한 예약 대기가 가능한 구조네요.
혹시 의도하신 걸까요?

2024-07-21 10:16 UTC, byjo commented on src/main/java/roomescape/service/ReservationService.java
> +			.status(ReservationStatus.WAITING.name())
Reservation의 status 타입이 String이 아닌 `ReservationStatus` 여도 되겠네요!

2024-07-21 10:16 UTC, byjo commented on src/main/java/roomescape/domain/Reservation.java
> +	public static void checkReservationAvailability(String date, String time) {
(지난 리뷰에 이어...)
validation 메서드가 Reservation 안으로 들어왔군요!

한 가지 우려되는 것은 예약일/시간에 따른 검증을 외부에서 능동적으로 이 메서드를 호출하여 수행해야 한다는 것인데요. 
`checkReservationAvailability` 메서드의 실행을 Reservation 인스턴스가 생성되는 시점에 진행한다면 이런 불편함이 사라질 것 같은데 어떠신가요?

2024-07-22 00:56 UTC, eottabom commented on src/main/java/roomescape/domain/Reservation.java
> +	public static void checkReservationAvailability(String date, String time) {
builder 에서 체크 할 수 있게 수정했어요! ㅎㅎ
https://github.com/next-step/spring-roomescape-waiting/pull/35/commits/104222f7ebd9f4c61c9b9d6a71dac7284144f35a#diff-5567764818950accf257c7b35753ce5e7fa067342af4fc8f885e5614b934c9a0R165

2024-07-22 00:56 UTC, eottabom commented on src/main/java/roomescape/service/ReservationService.java
> +			.status(ReservationStatus.WAITING.name())
String 이 아닌 `ReservationStatus` 로 변경했어요! 
https://github.com/next-step/spring-roomescape-waiting/pull/35/commits/104222f7ebd9f4c61c9b9d6a71dac7284144f35a#diff-5567764818950accf257c7b35753ce5e7fa067342af4fc8f885e5614b934c9a0R41

2024-07-22 00:57 UTC, eottabom commented on src/main/java/roomescape/service/ReservationService.java
> +		var theme = this.themeService.getThemeById(themeId);
이미 예약 대기를 한 경우에는
예약 대기를 할 수 없게 예외 처리했어요!
https://github.com/next-step/spring-roomescape-waiting/pull/35/commits/104222f7ebd9f4c61c9b9d6a71dac7284144f35a#diff-a08e170bf90a7f2fae99eafa05dfd10de6889b286503b78852bda8c78832cb3dR133

2024-07-22 01:00 UTC, eottabom commented on src/main/java/roomescape/repository/ReservationJpaRepository.java
> +	List<ReservationWithRank> findReservationsWithRankByMemberName(@Param("memberName") String memberName);
다른 방법 중에서는 예약과 예약 대기 테이블로 나누어서 할 수 있을 것 같은데,
그 경우에는 두 개의 테이블을 유지하고 관리해야한다는 불편함이 있을 것 같아요
(이 경우 쿼리도 복잡해질 수도 있을 것 같기도해요)

그래서 단순화 하기 위해서 reservation 테이블에 예약과 예약 대기를 모두 담기도록 하였어요!
아무래도 상태를 조금 더 유연하게 관리할 수 있을 것 같고, 상태 전환이 용이할 수 있을 것 같아요

하나의 테이블을 사용하면서 간소화된 쿼리를 사용할 수 있다는 장점이 있어서 선택하게 되었어요

2024-07-22 07:59 UTC, byjo approved these changes
피드백 반영까지 빠르게 잘 해주셨군요!
이번 미션에서 학습할 주제를 모두 소화하신 것 같아 이만 merge 할게요.
마지막 미션까지 마무리 하느라 고생 많으셨어요. 👏👏👏

2024-07-22 07:59 UTC, byjo commented on src/main/java/roomescape/repository/ReservationJpaRepository.java
> +	List<ReservationWithRank> findReservationsWithRankByMemberName(@Param("memberName") String memberName);
아하! 현재 상황에서는 단순하고 변경도 크지 않아 적절한 방법으로 보여요.
대신 테이블 row가 늘어나면 성능상의 이슈가 발생하기 쉬워보여 질문 드렸습니다 ㅎㅎ
미션은 마무리 되지만 이 부분도 함께 고민해보시면 좋을 것 같아요!

2024-07-22 07:59 UTC, byjo commented on src/test/java/roomescape/service/ReservationServiceTests.java
> +			.build();
테스트를 위한 인스턴스를 생성하는데서 많은 line을 차지하고 있네요.
헬퍼 메서드를 사용해도 좋을 것 같아요.
- [xUnit Patterns: Creation Method](http://xunitpatterns.com/Creation%20Method.html)

2024-07-22 07:59 UTC, merged